title       = "huobi"
baseURL     = "https://huobi-cli.tamnd.com/"
description = "A command line for huobi."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/huobi-cli"
